author="73mp74710n"
team="Nigeria Cyber Army"
eaddress="zombieleetnca@gmail.com"
bar===============================
opt="-n1"
PS2="BlackOrphan>"
prompt="${PS2}"
PS2="BlackOrphan"
createserver="${PS2}:create_server>"
vnum="_"
SPID="$$"
############################COLOR CODES#####################################
open="\e["
close="\e[0m"
bold="1;"
light="0;"
red="31m"
green="32m"
yellow="33m"
#blue="34m"
#white="1m"
new="\n"
CRYPT="${PWD}"
